### PR TITLE
Removes sound handling from NUI

### PR DESCRIPTION
**Pull request by Mojito-Fivem**
**Pull Request Description**

Gets rid of NAudio because it's NUI and uses native audio playing for ringtones. Ringtones in phone config.json need to be given nice names because chip thinks he's funny. Notification alerts are also done using native audio now.

**Pull Request Checklist**:
* [x] Have you followed the guidelines in our Contributing document and Code of Conduct?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/project-error/npwd/pulls) for the same update/change?
* [x] Have you built and tested NPWD in-game after the relevant change?

### CODE REVIEW

**Comment by Mojito-Fivem** [comment]
Draft because ringtones should probably have real names but im too lazy to name them

**Comment by Mojito-Fivem** [comment]
ok whatever github

**Comment by itschip** [comment]
We'll have to set the kvp value as well, when we update settings. Should be a nui callback in client/settings or so.

**Comment by Mojito-Fivem** [comment]
https://github.com/project-error/npwd/blob/dd07ead6cf3bc8078e54c41694f01613fc1c98eb/resources/client/settings/client-settings.ts#L7-L13 that's already being done here?

**Comment by itschip** [comment]
> that's already being done here?

Oh, well, then its fine.

**Comment by itschip** [comment]
Is even the 'NPWD_NOTIFICATION' used anywhere?

**Comment by Mojito-Fivem** [comment]
I can't find anything using it

**Comment by itschip** [comment]
> I can't find anything using it

Might as well just remove it then. Probably some left over stuff for when I was messing with sound sets.

**Comment by Mojito-Fivem** [comment]
This is all working now, the ringtones should probably be named something more exciting. All the traces of useSound and the sound provider in the nui have been removed and nothing seems to be broken.

**Comment by Mojito-Fivem** [comment]
This should pretty much done now if somebody wants to try it out and review the PR

**Comment by itschip** [comment]
> This should pretty much done now if somebody wants to try it out and review the PR

I'll test it later today :)

**Review by itschip — APPROVED** [review]

**Pull request merged**
