### PR TITLE
Create bg.json

### PR DESCRIPTION
**Pull request by JoroItalianeca**
Bulgarian Language

**Pull Request Description**

_Please include a general description of the changes made, why they were necessary, 
and any other general things to note._

**Pull Request Checklist**:
* [x] Have you followed the guidelines in our Contributing document and Code of Conduct?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/project-error/npwd/pulls) for the same update/change?
* [x] Have you built and tested NPWD in-game after the relevant change?

### CODE REVIEW

**Comment by itschip** [comment]
Please add this file to the `i18n.ts` file and the default settings file.

**Comment by itschip** [comment]
@JoroItalianeca any updates here?

**Comment by MJRamon** [comment]
Example: https://github.com/project-error/npwd/pull/593/files

**Comment by TasoOneAsia** [comment]
Closed due to inactivity, feel free to reopen once comments are taken into account.

**Pull request closed without merging**
