### PR TITLE
locale(ba): updated bosnian locale

### PR DESCRIPTION
**Pull request by katotekii**
**Pull Request Description**

_Please include a general description of the changes made, why they were necessary, 
and any other general things to note._

**Pull Request Checklist**:
* [ ] Have you followed the guidelines in our Contributing document and Code of Conduct?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/project-error/npwd/pulls) for the same update/change?
* [ ] Have you built and tested NPWD in-game after the relevant change?

### CODE REVIEW

**Review by anes66 — APPROVED** [review]
all translate good

**Comment by itschip** [comment]
@katotekii There has been some changes in master. Either rebase this branch with master, or if you don't know, we can just merge this, and you open a new PR with the rest of changes.

**Comment by katotekii** [comment]
I'll rebase this brantch later

**Comment by katotekii** [comment]
what exactly needs to be changed?

**Comment by itschip** [comment]
> what exactly needs to be changed?

There are new translations for Marketplace and Twitter

**Review by itschip — APPROVED** [review]

**Pull request merged**
