### PR TITLE
feat(phone/settings): call volume slider in settings

### LINKED ISSUE #483: Enhancement: Call Volume Slider in Settings
### Application

Settings

### Dependency

No

### Feature Description

As highlighted by #478, NPWD currently lacks anyway to control PMA voice's call volume. This should be added to the settings app.

### References

_No response_

### PR DESCRIPTION
**Pull request by TasoOneAsia**
**Pull Request Description**

This adds a slider to the settings app that will control the users phone call volume. 

Implements and closes #483 

Screen Shot 2022-01-04 at 1 50 37 PM

**Pull Request Checklist**:
* [x] Have you followed the guidelines in our Contributing document and Code of Conduct?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/project-error/npwd/pulls) for the same update/change?
* [x] Have you built and tested NPWD in-game after the relevant change?

**Additional Notes:**
This PR also allows for us to now easily access the NUI localStorage settings, once it has been loaded.

### CODE REVIEW

**Comment by RockySouthpaw** [comment]
This will also need to bump the release up to 1.1 as it’s a major feat change.

**Comment by TasoOneAsia** [comment]
> Also has the potential to break peoples NUI if they go back to a prior release

Migration is already handled through our localStorage manager.

**Review by itschip — CHANGES_REQUESTED** [review]

**Review by itschip — APPROVED** [review]

**Comment by TasoOneAsia** [comment]
@itschip Should we merge to master or should we hold in develop till a minor semver?

**Comment by itschip** [comment]
> @itschip Should we merge to master or should we hold in develop till a minor semver?

Let's merge this one to develop

**Pull request merged**
