### PR TITLE
feat(config): Add the ability to change used identifier type

### PR DESCRIPTION
**Pull request by Ekinoxx0**
Hi,

my server is currently using discord identifier to register users, and many other servers will be using steam ids.
So i'm suggesting make "license:" configurable for anyone would be a good idea.

Changing it from "license" to "discord" will not lead to any other issue from my testing as all identifier are string type even if they only contains number.

### CODE REVIEW

**Comment by itschip** [comment]
Could you please change branch to 'develop' and squash your commits? :)

**Comment by Ekinoxx0** [comment]
Just squashed the commit :)
Not sure if targeting to develop is a good idea as it 10 commits behind master for now 😅

Also, thanks for the quick answer

**Comment by itschip** [comment]
Yeah, you can either do the PR on your local 'develop', or we'll have to have to rebase. I don't like merging these type of commits to master.

**Comment by Ekinoxx0** [comment]
Closing this PR and making a new one from local develop branch as requested.
Totally understand you don't want merging this to master :)

**Pull request closed without merging**
