### PR TITLE
feat(config): added default config

### LINKED ISSUE #621: Enhancement: Implicit default config and config file language interoperability
### Application

Other

### Dependency

No

### Feature Description

We may be confusing users by presenting them too many options at one time in the `config.json` file. One approach to fix this would be to have an implicitly set default config, that is overwritten by a `config.json` and its keys. 

It may also be beneficial to allow for multiple configuration language files to be interoperable and is the norm in many NPM packages (as well as many libraries in general). This proposed interoperability would allow for `.yml, .json, or .js` configuration files to all be valid. Convar configurations should also be taken into account.

We could also go fully towards ConVars as the primary configuration approach. This should be discussed.

### References

**Valid ESLint Config Formats**
https://eslint.org/docs/user-guide/configuring/configuration-files

**Valid Prettier Config Formats**
https://prettier.io/docs/en/configuration.html

### PR DESCRIPTION
**Pull request by antonstjernquist**
Extend a base config to simplify setup.

**Pull Request Checklist**:
* [X] Have you followed the guidelines in our Contributing document and Code of Conduct?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/project-error/npwd/pulls) for the same update/change?
* [ ] Have you built and tested NPWD in-game after the relevant change?

### CODE REVIEW

**Comment by TasoOneAsia** [comment]
@Mojito-Fivem @c-wide Could I have somebody test this in-game for me? Don't currently have my dev environment setup post new c drive.

**Comment by Mojito-Fivem** [comment]
Can you rebase this from the develop branch @antonstjernquist

**Comment by Mojito-Fivem** [comment]
Built and loaded up in game it does appear to be working as intended

**Comment by TasoOneAsia** [comment]
All set to merge

**Comment by itschip** [comment]
> All set to merge

Lies

**Comment by itschip** [comment]
Isn't the docs for this already merged to master. Maybe fix the conflicts here and merge this, before someone tries to utilize this. @antonstjernquist

**Comment by Mojito-Fivem** [comment]
You could just change the base back to master branch and merge it in that case

**Comment by antonstjernquist** [comment]
> Isn't the docs for this already merged to master. Maybe fix the conflicts here and merge this, before someone tries to utilize this. @antonstjernquist 

There are no new features in this

**Comment by antonstjernquist** [comment]
> > All set to merge
> 
> Lies

It was pointing to master initially

**Review by itschip — APPROVED** [review]

**Pull request merged**
