### PR TITLE
fix(call): fix being able to accept calls if player has no phone

### PR DESCRIPTION
**Pull request by AvarianKnight**
**Pull Request Description**
Title says it all :P

**Pull Request Checklist**:
* [x] Have you followed the guidelines in our Contributing document and Code of Conduct?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/project-error/npwd/pulls) for the same update/change?
* [x] Have you built and tested NPWD in-game after the relevant change?

### CODE REVIEW

**Comment by RockySouthpaw** [comment]
This seems weird to even handle. People should just set the phone disabled if the item is removed and we should check if the phone is disabled on emiting messages and calls. 

Super weird to do an item check every single time especially when this shitty frameworks use server callbacks for them.

**Comment by AvarianKnight** [comment]
Both ways are not the greatest tbh, but this one is lighter on the server, at least for my framework as we don't use shitty callbacks to check items.

With setting the phone as disabled you then have the issue of people forgetting to change it back, so using the same export on the server would probably be a better idea.

**Comment by RockySouthpaw** [comment]
> Both ways are not the greatest tbh, but this one is lighter on the server, at least for my framework as we don't use shitty callbacks to check items.
> 
> With setting the phone as disabled you then have the issue of people forgetting to change it back, so using the same export on the server would probably be a better idea.

idk we need something that people with these xd RP frameworks won’t experience potential performance issues on larger pops

**Comment by RockySouthpaw** [comment]
@AvarianKnight Should the same logic be applied to notifications too? Or should that be dependent on phoneDisabled being true?

**Pull request merged**
