### PR TITLE
Refactor In-Phone Notifications

### PR DESCRIPTION
**Pull request by TasoOneAsia**
**Pull Request Description**
Notification system could use a refactor to enhance its UX. Here are some of the new proposed specifications.

**Feature Specs:**
* Should be animated with Grow transitions
* API should be declarative, the current one feels extremely imperative and delicate.
* Bridge to the SoundProvider should not have any transitive dependencies that cause unexpected behavior
* Expose notification layer to game scripts
* Basic action system embedded in notifications

**Tasks Progress**
- [x] Design presentation layer (animations, design)
- [x] Handle animations when phone is closed.
- [ ] Create fully fleshed API for notification system.
- [ ] Migrate apps from old notification system to new one.
- [ ] Add sound support
- [x] Expose phone notification export API (maybe?)
- [ ] Remove legacy notification system

**Pull Request Checklist**:
* [x] Have you followed the guidelines in our Contributing document and Code of Conduct?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/project-error/npwd/pulls) for the same update/change?
* [x] Have you built and tested NPWD in-game after the relevant change?

### CODE REVIEW

**Comment by TasoOneAsia** [comment]
Here is a short video showcasing new design and animations.

https://streamable.com/350u1x

**Comment by TasoOneAsia** [comment]
@RockySouthpaw @itschip. Can you guys take a look above and let me know what you guys think? Open to further feedback as well.

**Comment by RockySouthpaw** [comment]
> Expose notification layer to game scripts

this would be pogs for any future app implementation.

**Comment by TasoOneAsia** [comment]
> this would be pogs for any future app implementation.

I've actually exposed the initial queueNotification method to game scripts. Maybe this should be something exposed as an `npwd` export as well?

**Comment by RockySouthpaw** [comment]
Be sure to also to not use NUI to play any sounds Kappa

**Comment by RockySouthpaw** [comment]
> > this would be pogs for any future app implementation.
> 
> I've actually exposed the initial queueNotification method to game scripts. Maybe this should be something exposed as an `npwd` export as well?

yea an export would be ideal and easy to use for users as well. Easier to provide documentation too.

**Comment by TasoOneAsia** [comment]
Now pending me testing in-game for migration work.

**Comment by MJRamon** [comment]
Could entering and leaving animations use position, not height, so they will slide in and slide out, instead of "scan" effect?

**Pull request closed without merging**
