### PR TITLE
feat(messages): location pinging

### PR DESCRIPTION
**Pull request by Mojito-Fivem**
**Pull Request Description**
Implements a share location feature in the messages app ctx menu as outlined in #711 . This allows people to share their location with the ability to set a waypoint. 

**Pull Request Checklist**:
* [x] Have you followed the guidelines in our Contributing document and Code of Conduct?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/project-error/npwd/pulls) for the same update/change?
* [x] Have you built and tested NPWD in-game after the relevant change?

### CODE REVIEW

**Comment by Mojito-Fivem** [comment]
> Maybe instead of getting the player name for display, get contact name or phone number?

I disagree to be honest, the display name makes the most sense here

**Comment by Patilhas** [comment]
> > Maybe instead of getting the player name for display, get contact name or phone number?
> 
> I disagree to be honest, the display name makes the most sense here, also for groups etc the contact name won't be the same for everyone. From the server it's either the character name or phone number we can get and I would say the name makes more sense.

It's just because, I'm going for a roleplay perspective right now. I'm talking to someone I don't know, it does really make sense to know his real name on the server when I didn't knew it before? It is a thing that can be easily changed. 

But you could also get the contact based on the number that sent the location on rendering if anyone wants to change it.

**Comment by Mojito-Fivem** [comment]
From a roleplay perspective, If I have somebody's phone number I probably also know their name

**Comment by Patilhas** [comment]
> From a roleplay perspective, If I have somebody's phone number I probably also know their name

There are a few exceptions especially in the crime world, but they exist. But as I said before, someone who has a little knowledge with the npwd codebase can change it easily.

**Comment by Mojito-Fivem** [comment]
I'll leave it open to discussion and get some more opinions, as you said it shouldn't be too difficult to implement it that way.

**Comment by AvaN0x** [comment]
> I'll leave it open to discussion and get some more opinions, as you said it shouldn't be too difficult to implement it that way.

I agree with @Patilhas, it can happen that you won't know the name of the person even if you have their number, or not their real name (in case of somebody who give a fake name for some reasons).
What I would suggest is either the conversation name, the phone number or a custom label that the user has to enter when sending coordinates *(could default to the phone number and still allow to set a custom label)*.

**Comment by Mojito-Fivem** [comment]
Alright, it now uses the contact name or defaults to their phone number if you don't have them saved.

**Comment by Mojito-Fivem** [comment]
image
image

**Pull request merged**
