### PR TITLE
feat(locale/es): update to new translations

### PR DESCRIPTION
**Pull request by BombayV**
**Pull Request Description**

Should be everything needed from the current English translations. However, when testing with Rocko there were some missing keys for the en.json so I don't know if more are going to be needed.

**Pull Request Checklist**:
* [X] Have you followed the guidelines in our Contributing document and Code of Conduct?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/project-error/npwd/pulls) for the same update/change?
* [ ] Have you built and tested NPWD in-game after the relevant change? _Only tested in browser_

### CODE REVIEW

**Review by itschip — APPROVED** [review]

**Comment by TasoOneAsia** [comment]
> However, when testing with Rocko there were some missing keys.

Let's resolve these before merging.

**Comment by RockySouthpaw** [comment]
> However, when testing with Rocko there were some missing keys for the en.json so I don't know if more are going to be needed.
Sauce?

**Comment by itschip** [comment]
@BombayV Are there any other missing keys?

**Comment by BombayV** [comment]
> @BombayV Are there any other missing keys?

I have no idea if you added more. I added the ones the `en.json` had at the time,

**Comment by TasoOneAsia** [comment]
As per release, this should be moved up to merge.

**Comment by RockySouthpaw** [comment]
Tested, looks fine. If there any more missing ones we'll just need to address that as they come.

**Pull request merged**
