### PR TITLE
fix(phone/twitter): Remove 'xd' from button

### PR DESCRIPTION
**Pull request by antond15**
**Pull Request Description**

Removed possible leftover (`xd`) from "Choose image" button in Twitter profile settings.

**Pull Request Checklist**:
* [x] Have you followed the guidelines in our Contributing document and Code of Conduct?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/project-error/npwd/pulls) for the same update/change?
* [x] Have you built and tested NPWD in-game after the relevant change?

### CODE REVIEW

**Comment by TasoOneAsia** [comment]
This should be fine but CI is failing, try rebasing against master.

**Comment by TasoOneAsia** [comment]
Ah I see, its because your base branch is develop.

**Comment by itschip** [comment]
XD

**Comment by TasoOneAsia** [comment]
Merged with 17d508dbcfca30feb57b0ee4fda7d364f141af50

**Pull request closed without merging**
