### PR TITLE
Migrate to Material UI v5

### PR DESCRIPTION
**Pull request by TasoOneAsia**
Material UI Version 5 is currently in the beta testing phase. It would be prudent to ensure that we are able of migrating easily and effectively. This PR will be a WIP PR with some of the changes required to make this possible.

Migration process was done either according to [here](https://next.material-ui.com/guides/migration-v4/), or with general knowledge about some of the changes.

### CODE REVIEW

**Comment by itschip** [comment]
I'll do a quick test of this today.

**Comment by TasoOneAsia** [comment]
This needs to be updated against develop branch

**Comment by itschip** [comment]
`History` view in dialer app has white icons, while `Contacts` view has green icons. Let's maybe try and stick with one of them.

**Review by itschip — APPROVED** [review]

**Comment by itschip** [comment]
Dragging cards in Matchmaker seems to have a bug, where it slides vertically.

**Pull request merged**
