### PR TITLE
Bug fixes v2

### PR DESCRIPTION
**Pull request by AvarianKnight**

### CODE REVIEW

**Comment by TasoOneAsia** [comment]
I wasn't able to review your last PR and I am on phone right now, but that animation service class seems to have a lot of unnecessary async methods.

**Comment by AvarianKnight** [comment]
> I wasn't able to review your last PR and I am on phone right now, but that animation service class seems to have a lot of unnecessary async methods.

You're correct, a lot of them were from original code, almost all of the async is likely not needed anymore as its constantly updated now, so it being async wont even matter

**Comment by itschip** [comment]
@AvarianKnight Please switch branch to 'develop', not 'master'.

**Comment by itschip** [comment]
Seems like you got some conflicts here, *buddy*.

**Comment by RockySouthpaw** [comment]
@AvarianKnight please resolve the conflicts, *buddy*

**Comment by AvarianKnight** [comment]
Pretty sure there's a bunch of conflicts because everything that was in this was already done on develop :P

**Pull request closed without merging**
