### PR TITLE
feat(locale): Add italian and finnish translation 

### PR DESCRIPTION
**Pull request by Xxpromw3mtxX**
**Pull Request Description**

_Please include a general description of the changes made, why they were necessary, 
and any other general things to note._

**Pull Request Checklist**:
* [x] Have you followed the guidelines in our Contributing document and Code of Conduct?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/project-error/npwd/pulls) for the same update/change?
* [x] Have you built and tested NPWD in-game after the relevant change?

### CODE REVIEW

**Comment by itschip** [comment]
You have changes in the 'yarn.lock' file, please remove such from this PR.

**Comment by TasoOneAsia** [comment]
Is this PR adding both Finnish and Italian?

**Comment by Xxpromw3mtxX** [comment]
Yes, I've cloned the original that conatined Finnish and re-added Italian

**Comment by TasoOneAsia** [comment]
Do you mind solving conflicts, and I'll look into merging this?

**Comment by Xxpromw3mtxX** [comment]
Ok, solved!
I forgot to do it, my bad!

**Comment by TasoOneAsia** [comment]
It appears that Finnish has already been added with this commit. I don't believe this PR needs to add it.

https://github.com/project-error/npwd/commit/404ad9d09d4e01c952621fe6ba7632d81b972fbf

**Comment by Xxpromw3mtxX** [comment]
Should I open another PR with only italian?

**Comment by TasoOneAsia** [comment]
> Should I open another PR with only italian?

Probably best unless you are extremely comfortable with Git commands.

**Comment by Xxpromw3mtxX** [comment]
I'll go with the first, haven't used the cli in a while

**Pull request closed without merging**
