### PR TITLE
feat(locale/hu): Update outdated Hungarian locale file

### PR DESCRIPTION
**Pull request by Rav3n95**
**Updated Hungarian language**

_The old file was  outdated._

### CODE REVIEW

**Comment by TasoOneAsia** [comment]
@Rav3n95 Looks like our CI failed because your JSON is invalid. Do you mind fixing that and then I can merge it?

**Comment by Rav3n95** [comment]
> @Rav3n95 Looks like our CI failed because your JSON is invalid. Do you mind fixing that and then I can merge it?

Ye i think i found the problem, im kinda new to github, so i dont know how to edit it.

**Comment by TasoOneAsia** [comment]
> Ye i think i found the problem, im kinda new to github, so i dont know how to edit it.

You need to push any changes to the `patch-1` branch of your fork.

**Comment by Rav3n95** [comment]
> > Ye i think i found the problem, im kinda new to github, so i dont know how to edit it.
> 
> You need to push any changes to the `patch-1` branch of your fork.

Yea, i already deleted that..

**Pull request closed without merging**
